# Generated by Django 3.1.7 on 2021-02-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
